---
- name: build app
  hosts: web
  become: yes

  tasks:
  - name: ensure java package is present
    apt:
      name: openjdk-8-jdk
      state: present

  - name: ensure project is cloned
    git:
      clone: yes
      repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello
      dest: /tmp/test2

  - name: ensure mvn package is present
    apt:
      name: maven
      state: present

  - name: ensure tomcat package is present
    apt:
      name: tomcat8
      state: present

  - name: ensure tomcat service is started
    service:
      name: tomcat8
      state: started

  - name: maven package
    command: mvn -f /tmp/test2/pom.xml package

  - name: copy war to tomcat dir
    command: cp /tmp/test2/target/hello-1.0.war /var/lib/tomcat8/webapps/
